# Generated by Django 5.2.15 on 2026-07-06 14:48

import carpool.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('families', '0002_activity'),
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarpoolGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('invite_code', models.CharField(default=carpool.models.generate_invite_code, max_length=16, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='carpool_groups_created', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carpool_groups', to='schools.school')),
            ],
            options={
                'db_table': 'carpool_groups',
            },
        ),
        migrations.CreateModel(
            name='CarpoolAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('suggested', 'Suggested'), ('confirmed', 'Confirmed'), ('swap_pending', 'Swap Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='suggested', max_length=15)),
                ('is_auto_suggested', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver_family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driving_assignments', to='families.family')),
                ('driver_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driving_assignments', to=settings.AUTH_USER_MODEL)),
                ('carpool_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='carpool.carpoolgroup')),
            ],
            options={
                'db_table': 'carpool_assignments',
            },
        ),
        migrations.CreateModel(
            name='CarpoolGroupMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('member', 'Member')], default='member', max_length=10)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('carpool_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='carpool.carpoolgroup')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carpool_memberships', to='families.family')),
            ],
            options={
                'db_table': 'carpool_group_members',
            },
        ),
        migrations.CreateModel(
            name='CarpoolRotationRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rotation_type', models.CharField(choices=[('round_robin', 'Round Robin'), ('weighted', 'Weighted'), ('manual_only', 'Manual Only')], max_length=20)),
                ('cycle_days', models.JSONField()),
                ('start_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('carpool_group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rotation_rule', to='carpool.carpoolgroup')),
            ],
            options={
                'db_table': 'carpool_rotation_rules',
            },
        ),
        migrations.CreateModel(
            name='CarpoolRotationOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.IntegerField()),
                ('weight', models.IntegerField(default=1)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotation_positions', to='families.family')),
                ('rotation_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_entries', to='carpool.carpoolrotationrule')),
            ],
            options={
                'db_table': 'carpool_rotation_order',
            },
        ),
        migrations.CreateModel(
            name='CarpoolSwapRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=10)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_requests', to='carpool.carpoolassignment')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_requests_made', to=settings.AUTH_USER_MODEL)),
                ('target_family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_requests_received', to='families.family')),
            ],
            options={
                'db_table': 'carpool_swap_requests',
            },
        ),
        migrations.AddConstraint(
            model_name='carpoolassignment',
            constraint=models.UniqueConstraint(fields=('carpool_group', 'date'), name='unique_group_date'),
        ),
        migrations.AddConstraint(
            model_name='carpoolgroupmember',
            constraint=models.UniqueConstraint(fields=('carpool_group', 'family'), name='unique_group_family'),
        ),
        migrations.AddConstraint(
            model_name='carpoolrotationorder',
            constraint=models.UniqueConstraint(fields=('rotation_rule', 'position'), name='unique_rule_position'),
        ),
    ]
