# Generated by Django 5.2.15 on 2026-07-06 22:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0001_initial'),
        ('families', '0002_activity'),
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickupEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('pickup_method', models.CharField(choices=[('parent', 'Parent'), ('carpool', 'Carpool'), ('aftercare', 'Aftercare'), ('bus', 'Bus'), ('walker', 'Walker')], default='parent', max_length=10)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('en_route', 'En Route'), ('arrived', 'Arrived'), ('picked_up', 'Picked Up'), ('missed', 'Missed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=10)),
                ('scheduled_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('carpool_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_events', to='carpool.carpoolassignment')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_events', to='families.child')),
                ('trip_stop_child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_events', to='trips.tripstopchild')),
            ],
            options={
                'db_table': 'pickup_events',
                'indexes': [models.Index(fields=['date'], name='pickup_date_idx'), models.Index(fields=['child', 'date'], name='pickup_child_date_idx')],
                'constraints': [models.UniqueConstraint(fields=('child', 'date'), name='unique_child_date_pickup')],
            },
        ),
    ]
